import { CheckCircle, Target, Eye, Heart } from 'lucide-react';
import { useInView } from '../hooks/useInView';

function Reveal({ children, className = '', delay = '' }: { children: React.ReactNode; className?: string; delay?: string }) {
  const { ref, inView } = useInView();
  return <div ref={ref} className={`${className} ${inView ? `animate-fade-up ${delay}` : 'opacity-0'}`}>{children}</div>;
}

export default function About() {
  return <div className="page-enter pt-20 bg-white">
    <section className="relative py-24 bg-[#071d38] overflow-hidden"><div className="absolute inset-0 opacity-25 bg-[url('https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1800&q=85')] bg-cover bg-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#06172e] via-[#082c49]/90 to-[#008e9e]/45"/><div className="relative max-w-7xl mx-auto px-5"><p className="text-cyan-300 uppercase tracking-[.25em] text-xs font-bold">Who We Are</p><h1 className="text-white text-5xl md:text-6xl font-extrabold mt-3">About KAM Internal Auditors Inc.</h1><p className="text-slate-200 mt-5 max-w-3xl text-lg leading-8">A fast-growing 100% black-owned professional services firm established in 2021, serving public and private organisations with audit, advisory, taxation, ICT and business support services.</p></div></section>
    <section className="py-20"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-14 items-center"><Reveal><div className="grid grid-cols-2 gap-4"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85" alt="Professional audit team" className="w-full h-56 object-cover rounded-3xl shadow-xl"/><img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=900&q=85" alt="Professional consulting team" className="w-full h-56 object-cover rounded-3xl shadow-xl mt-8"/><img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=85" alt="Financial review meeting" className="w-full h-56 object-cover rounded-3xl shadow-xl -mt-8"/><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85" alt="Modern professional office" className="w-full h-56 object-cover rounded-3xl shadow-xl"/></div></Reveal><Reveal><p className="text-cyan-600 uppercase tracking-widest text-xs font-bold">Company Introduction</p><h2 className="text-4xl md:text-5xl font-extrabold text-[#08213f] mt-3 mb-5">Professional Expertise. Modern Solutions.</h2><p className="text-slate-600 leading-7 mb-4">KAM Internal Auditors Inc. is registered with the South African Institute of Chartered Accountants (SAICA) and South African Revenue Services (SARS) as a Tax Practitioner.</p><p className="text-slate-600 leading-7 mb-4">Our experienced internal auditors are registered members of the Institute of Internal Auditors South Africa (IIASA).</p><p className="text-slate-600 leading-7 mb-6">We support municipalities, universities, TVET colleges, NPOs, departments, public entities and private companies with professional audit, governance, finance, tax and ICT services.</p><div className="grid sm:grid-cols-2 gap-3">{['100% Black-Owned','Established in 2021','SAICA & SARS Registered','IIASA Registered Auditors'].map(v=><div key={v} className="flex items-center gap-2 text-sm font-semibold text-[#08213f]"><CheckCircle size={18} className="text-cyan-500"/>{v}</div>)}</div></Reveal></div></section>
    <section className="py-20 bg-slate-50"><div className="max-w-7xl mx-auto px-5"><div className="grid md:grid-cols-3 gap-8">{[{icon:<Eye/>,title:'Our Vision',text:'To become a leading and highly innovative audit, advisory, ICT, and business solutions provider recognized for excellence, professionalism, and client-centered service delivery.'},{icon:<Target/>,title:'Our Mission',text:'To deliver efficient, professional, and innovative solutions that help clients improve governance, strengthen internal controls, enhance operational performance, and embrace modern technology systems.'},{icon:<Heart/>,title:'Our Values',text:'Professionalism, integrity, excellence, commitment, continuous improvement, innovation, teamwork and client satisfaction.'}].map((item,i)=><Reveal key={item.title} delay={`delay-${(i+1)*100}`}><div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 h-full hover:-translate-y-1 hover:shadow-xl transition"><div className="w-14 h-14 rounded-2xl bg-cyan-50 text-cyan-600 flex items-center justify-center mb-5">{item.icon}</div><h3 className="text-2xl font-extrabold text-[#08213f] mb-3">{item.title}</h3><p className="text-slate-600 leading-7 text-sm">{item.text}</p></div></Reveal>)}</div></div></section>
  </div>;
}
