import { useState } from 'react';
import { X, ZoomIn } from 'lucide-react';
import { useInView } from '../hooks/useInView';

const IMAGES = [
  { src:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85', cat:'Audit', title:'Internal Audit Review' },
  { src:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=85', cat:'Finance', title:'Financial Advisory Session' },
  { src:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=85', cat:'Tax', title:'Tax & Financial Planning' },
  { src:'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85', cat:'Governance', title:'Governance Team Workshop' },
  { src:'https://images.unsplash.com/photo-1589578527966-fdac0f44566c?auto=format&fit=crop&w=1200&q=85', cat:'Compliance', title:'Compliance & Investigation Review' },
  { src:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85', cat:'ICT', title:'ICT Systems & Support' },
  { src:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85', cat:'Assets', title:'Asset Management Support' },
  { src:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85', cat:'Advisory', title:'Professional Advisory Environment' },
];
const CATS=['All',...Array.from(new Set(IMAGES.map(i=>i.cat)))];
function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const{ref,inView}=useInView();return <div ref={ref} className={`${className} ${inView?'animate-scale-in':'opacity-0'}`}>{children}</div>}
export default function Gallery(){const[filter,setFilter]=useState('All');const[lightbox,setLightbox]=useState<typeof IMAGES[0]|null>(null);const filtered=filter==='All'?IMAGES:IMAGES.filter(i=>i.cat===filter);return <div className="page-enter pt-20 bg-white"><section className="relative py-24 bg-[#071d38] overflow-hidden"><div className="absolute inset-0 opacity-25 bg-[url('https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=85')] bg-cover bg-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#06172e] via-[#082c49]/90 to-[#008e9e]/40"/><div className="relative max-w-7xl mx-auto px-5"><p className="text-cyan-300 uppercase tracking-[.25em] text-xs font-bold">Professional Services in Action</p><h1 className="text-white text-5xl md:text-6xl font-extrabold mt-3">Gallery</h1><p className="text-slate-200 mt-5 max-w-2xl text-lg">A visual overview of the professional environments, disciplines and solutions represented by KAM Internal Auditors Inc.</p></div></section><section className="py-8 border-b border-slate-100 sticky top-20 z-20 bg-white/95 backdrop-blur"><div className="max-w-7xl mx-auto px-5 flex flex-wrap gap-2 justify-center">{CATS.map(cat=><button key={cat} onClick={()=>setFilter(cat)} className={`px-5 py-2 rounded-full text-sm font-semibold transition ${filter===cat?'bg-cyan-600 text-white':'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{cat}</button>)}</div></section><section className="py-16 bg-slate-50"><div className="max-w-7xl mx-auto px-5 grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">{filtered.map(item=><Reveal key={item.src}><button onClick={()=>setLightbox(item)} className="relative w-full h-64 rounded-3xl overflow-hidden shadow-sm group text-left"><img src={item.src} alt={item.title} className="w-full h-full object-cover group-hover:scale-105 transition duration-500"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent"/><div className="absolute bottom-0 p-4"><p className="text-white font-bold">{item.title}</p><span className="text-cyan-300 text-xs">{item.cat}</span></div><ZoomIn className="absolute top-4 right-4 text-white opacity-0 group-hover:opacity-100 transition"/></button></Reveal>)}</div></section>{lightbox&&<div onClick={()=>setLightbox(null)} className="fixed inset-0 z-[90] bg-black/90 p-4 flex items-center justify-center"><button className="absolute top-5 right-5 text-white"><X/></button><div onClick={e=>e.stopPropagation()} className="max-w-5xl w-full"><img src={lightbox.src} alt={lightbox.title} className="w-full max-h-[80vh] object-contain rounded-2xl"/><p className="text-center text-white mt-4 font-bold">{lightbox.title}</p></div></div>}</div>}
